# Generated by Django 4.0.5 on 2022-07-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curslar', '0002_rename_duration_courses_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=150, verbose_name='имя'),
        ),
    ]
