# Generated by Django 4.0.5 on 2022-07-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curslar', '0004_courses_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='idx',
        ),
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
